title: Github Page of DigiTechPoint
email: sam@digitechpoint.com
description: Github Page of DigiTechPoint
baseurl: "" #the subpath of your site, e.g. /blog
url: "https://digitechpoint.github.io" # the base hostname & protocol for your site

# about 5 elements are recomended
github_username:  digitechpoint
facebook_username: digitechpoint
google_plus_username: 107242752933041005904
instagram_username:  digitechpoint

avatar: yes
avatar_img_path: "https://avatars2.githubusercontent.com/u/14108051"


front_img: yes
front_img_path: "imgs/background.jpg"

favicon_img: yes
favicon_img_path: "https://avatars2.githubusercontent.com/u/14108051"

# Build settings
markdown: kramdown
permalink: /:title.htm
